### ISSUE TITLE
Replace kallisto Dockerfile without conda

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/Dockerfiles#61]
Replace [kallisto Dockerfile](https://github.com/zavolanlab/Dockerfiles/blob/master/kallisto/0.46.1/Dockerfile) to install kallisto without conda 

The current image cannot be pulled on OSX via singularity. Related to https://github.com/sylabs/singularity/issues/4301

**Comment by AngryMaciek** [comment]
Does that mean that all images with `base:miniconda3` and software installed by `conda` might not work on Mac?

**Comment by fgypas** [comment]
I think this is something that will be fixed by singularity. But for the time being it might cause some problems. Also, note that singularity for mac is still in beta.
